ithacaxyz/odyssey

- README.md
Updating the readme regarding the testnet as as described [here](https://www.ithaca.xyz/updates/odyssey#how-do-i-try-out-odyssey)
> (EDIT): Edit Readme to reflect Testnet being live

- crates/wallet/src/lib.rs
Limit the gas usage by sequencer sponsored transactions. The limit was chosen arbitrarily
> fix: limit gas usage by sequencer tx

- crates/wallet/src/lib.rs
Small stylistic nit, since we do it like this for the other fields
> chore: set gas limit directly

- crates/wallet/src/lib.rs
Adds some basic tests for `validate_tx_request`
> test: basic tx validation tests

- Cargo.lock
- Cargo.toml
- crates/node/Cargo.toml
- crates/node/src/chainspec.rs
Replace `once_cell::sync::Lazy` with `std::sync::LazyLock`
Since we are on `msrv` > 1.80
> feat: replace `once_cell` with std

- crates/wallet/src/lib.rs
This PR improves the performance of gas estimation and fee calculation by running both tasks concurrently using tokio::join!. This change reduces the overall execution time by allowing the two independent operations to proceed in parallel, rather than sequentially
> chore:: optimize Gas Estimation and Fee Calculation using tokio::join!

- crates/wallet/src/lib.rs
In some cases `tx.origin` might be checked, so we should set `from` in the request, otherwise these calls revert
> fix: set from field when estimating gas

- Cargo.lock
- Cargo.toml
- bin/odyssey/src/main.rs
- crates/node/src/node.rs
smol breaking change on builder API, make the manual sequencer installation redundant
> chore: bump reth 7b1b1fc

- Makefile
Add more `make` commands to clean, format and lint code easier.
> chore(make): add clean, fmt, lint

- .github/workflows/e2e.yml
Send a simple tx to replica before running tests. This would add it to the pool and await replica receiving a block with this transaction, thus flipping the `prague` fork activation here https://github.com/paradigmxyz/reth/blob/0a1473b6e7949875f480043fa6874bdc583786d2/crates/transaction-pool/src/validate/eth.rs#L467
This is a workaround until we figure out why replica is not able to receive blocks from sequencer over p2p right away after the launch
> fix(e2e): make sure replica receives a block

- README.md
> chore: switch optimism-package fork

- .github/workflows/e2e.yml
- etc/kurtosis.yaml
Uses https://github.com/ethpandaops/optimism-package/pull/85 for now, once merged can be replaced with upstream package.
This also switches to using images from https://github.com/paradigmxyz/optimism cc @Rjected
> сhore: use upstream kurtosis package

- Cargo.lock
- bin/odyssey/Cargo.toml
- crates/precompile/Cargo.toml
Random `cargo machete` run. Also wonder if we're still maintaining `alphanet`?
> chore: remove unused deps

- crates/wallet/src/lib.rs
> fix: use next available nonce for tx

- .github/workflows/e2e.yml
upstream PR is still in review, so locking this for now so that we're not affected by changes applied during review
> fix: freeze commit for e2e optimism-package

- README.md
Seems to be rendering incorrectly, see screenshot:
> docs: fix Markdown notice block in README

- .github/workflows/e2e.yml
- README.md
- etc/kurtosis.yaml
Uses https://github.com/ethpandaops/optimism-package directly and updates README a bit as we no more need to build contract deployer image separately
Also removed hack from https://github.com/ithacaxyz/odyssey/pull/52 as it shouldn't be needed after https://github.com/paradigmxyz/reth/pull/11847
> chore: migrate to upstream kurtosis package

- crates/walltime/src/lib.rs
These variables were flipped from their intended meanings.
See: https://github.com/transmissions11/reth-walltime/blob/15218b6d66c8da339bab541aa71373aaceb66165/bin/reth/src/optimism.rs#L170-L171
> fix(walltime): flip block_timestamp/wall_time_ms

- Cargo.lock
- Cargo.toml
- bin/odyssey/src/main.rs
- crates/node/Cargo.toml
- crates/node/src/chainspec.rs
- crates/node/src/evm.rs
- crates/node/src/node.rs
- crates/wallet/Cargo.toml
- crates/wallet/src/lib.rs
Bumps everything basically and essentially
> chore: bump alloy and reth

- Cargo.lock
- bin/odyssey/src/main.rs
- crates/node/Cargo.toml
- crates/node/src/broadcaster.rs
- crates/node/src/lib.rs
closes https://github.com/ithacaxyz/odyssey/issues/103
Adds a service that every 10 minutes re-broadcasts transactions belonging to the sponsor from the txpool
> feat: add periodic broadcaster

- bin/odyssey/src/main.rs
- crates/e2e-tests/src/tests.rs
- crates/wallet/src/lib.rs
Closes #99 
Removed `get_capabilities` from the `WalletCapabilities` trait
In `e2e_tests` the capabilities is initialised manually with the contract address being pulled in from `env` variables.
Related PR: https://github.com/ithacaxyz/odyssey/pull/104#pullrequestreview-2479776747
> feat: Remove wallet_getCapabilities

- Cargo.lock
- bin/odyssey/src/main.rs
- crates/node/Cargo.toml
- crates/node/src/forwarder.rs
- crates/node/src/lib.rs
- crates/node/src/node.rs
this adds sequencer forwarding if the transaction was received via eth_sendrawtransaction
> feat: forward txns over p2p

- Cargo.lock
- bin/odyssey/Cargo.toml
re https://github.com/paradigmxyz/reth/pull/12178
opening this so we don't forget to enable it after next reth bump
> chore: activate js-tracer

- .config/nextest.toml
- Providing a more specific package reference prevents potential conflicts if packages with similar names emerge.
- This aligns with the current recommendations in the Nextest documentation.
- It improves the readability of the configuration for other developers.
> ci: use exact nextext filter

- .github/workflows/integration.yml
This PR updates the integration tests workflow configuration to follow modern best practices and improve test output visibility.
- Added `--profile ci` flag to nextest configuration for better CI integration and consistency
- Replaced deprecated `--no-tests=warn` flag with modern `--no-capture` flag for better test output visibility
- Updated `re-actors/alls-green` action from `release/v1` to specific version `v1.2.2` for improved stability
- Improves test output readability in CI environment
- Updates deprecated test configuration to modern standards
- Pins action version for better reproducibility
- Makes integration tests configuration consistent with other workflows
- Integration tests workflow has been tested and works as expected
- Test outputs are now more verbose and easier to …
> chore(ci): improve integration tests configuration

- crates/e2e-tests/src/tests.rs
This pull request enhances the end-to-end test suite by improving error handling, adding documentation, and refactoring code for better maintainability.
- **Documentation Enhancements:**
- Added detailed comments for each test function to describe their purpose and functionality.
- Improved error messages for environment variable parsing to provide clearer feedback.
- **Code Refactoring:**
- Introduced constants for frequently used values such as `TEST_PRIVATE_KEY` and `DEFAULT_DELEGATION_ADDRESS` to improve code readability and maintainability.
- Refactored the `assert_chain_advances` test to use a single provider instance and added a more informative assertion message.
- **Test Improvements:**
- Enhanced the `test_wallet_api` to include more descriptive assertions and comments.
- Added …
> test: improve e2e test coverage and documentation

- Cargo.lock
- Cargo.toml
- bin/odyssey/Cargo.toml
- bin/relay/Cargo.toml
- bin/relay/src/main.rs
Set CORS headers in the relay service
> feat: cors

- crates/node/src/evm.rs
Closes #125 
Added `P256Verify` precompile to the `0x100` address and a test to check its availability at both the addresses
The test is currently failing, and I'm not entirely sure about my implementation of test function. It might be causing the test to fail. 
lmk of any suggestions @onbjerg
> feat: added P256Verify precompile to 0x100

- Cargo.lock
- Cargo.toml
- bin/relay/Cargo.toml
- bin/relay/src/main.rs
Be explicit about origins, HTTP methods and HTTP headers in CORS policy
> chore: more explicit cors policy

- crates/node/src/evm.rs
Hi! In this pull request, I fixed a broken link in the `evm.rs` file. The old reference to `EIP-7212` was replaced with the correct link to `RIP-7212`. Following [EIP-7607](https://eips.ethereum.org/EIPS/eip-7607#considered-for-inclusion), the link and label were updated to align with the correct RIP specification.
> fix: broken link EIP-7212 evm.rs

- crates/node/src/broadcaster.rs
I noticed a discrepancy in the timer interval for transaction rebroadcasting. The code currently sets the interval to 60 seconds (1 minute), but the comment above clearly states that transactions should be rebroadcast every 10 minutes. I've updated the value to `600` seconds to align with the intended behavior.  
Here's the corrected line:  
```rust  
let mut interval_timer = tokio::time::interval(Duration::from_secs(600));  
```  
This change ensures the functionality matches the documented logic.
> chore: Fix transaction rebroadcast interval to match intended 10-m delay

- .github/workflows/e2e.yml
- etc/kurtosis.yaml
Fixes error in the kurtosis e2e tests: 
```
Caused by: Unexpected error occurred starting service 'el-1-reth-lighthouse'
Caused by: An error occurred waiting for all TCP and UDP ports to be open for service 'el-1-reth-lighthouse' with private IP '172.16.0.10'; this is usually due to a misconfiguration in the service itself, so here are the logs:
== SERVICE 'el-1-reth-lighthouse' LOGS ===================================
error: unexpected argument '--rpc.eth-proof-window 100' found
tip: a similar argument exists: '--rpc.eth-proof-window'
```
Transitions to pectra instead of setting at genesis because currently kurtosis does not appear to work when enabling electra at genesis. The deterministic deployer has to be set at genesis, so it's added as a predeploy. This also waits for block 32, …
> fix(ci): use prysm and fix proof window command

- crates/node/src/evm.rs
I removed the duplicate condition for `EthereumHardfork::Prague` that appeared twice in the code.
Now, it’s present only once, ensuring cleaner and more efficient logic.
> fix: fix Duplicate Condition for EthereumHardfork::Prague

- README.md
Hi! I updated the link for `RIP-7212` in README.md because the new link provides more specific and up-to-date information about `RIP-7212`. This change will help developers find the necessary details more quickly and also allow them, if needed, to navigate to the forum or other resources directly from this [page](https://github.com/ethereum/RIPs/blob/master/RIPS/rip-7212.md).
> docs: update link RIP-7212 in `README.md`

- crates/e2e-tests/src/tests.rs
Noticed that `get_code_at(signer.address())` can return `None`, which causes a panic when calling `.is_empty()`.
Now using `unwrap_or_default()` to prevent this issue.
P.S. Everything works fine, and tests pass.
> fix: fix panic when `get_code_at` returns `None`

- .github/workflows/e2e.yml
- .github/workflows/lint.yml
- Cargo.lock
- Cargo.toml
- bin/odyssey/Cargo.toml
- bin/odyssey/src/main.rs
- bin/relay/Cargo.toml
- bin/relay/src/main.rs
- crates/e2e-tests/Cargo.toml
- crates/e2e-tests/src/tests.rs
- crates/node/Cargo.toml
- crates/node/src/delayed_resolve.rs
- crates/node/src/node.rs
- crates/wallet/Cargo.toml
- crates/wallet/src/lib.rs
Closes #162 
Bumps all the `reth` and `alloy` dependencies to latest.
Note the change in genesis configuration.
> build(deps): Upgrade `reth` version `1.3.8` => `1.3.12` and `alloy` version `0.13` => `0.15`

- Cargo.lock
- Cargo.toml
- bin/odyssey/Cargo.toml
- crates/node/Cargo.toml
- crates/node/src/broadcaster.rs
- crates/node/src/chainspec.rs
- crates/node/src/delayed_resolve.rs
- crates/node/src/forwarder.rs
- crates/node/src/lib.rs
- crates/node/src/node.rs
- crates/walltime/Cargo.toml
> The Cargo.toml file has a lot of reth dependencies, reth recently added the reth-op crate which re-exports all of the crates behind feature flags. Try to transition the dependencies of the crates in this workspace to reth-op enabling the necessary features (node or full and cli). Similar migrations have been made to the crates in the reth repository's examples folder, which can be a helpful reference for this task.
> 
> In addition to that remove unused dependencies from this workspace dependencies
>
> try to reduce individual reth- crate dependencies in crates/node by replacing them with a reth_op dependency with the full and cli feature and update the use statements accordingly so they use the re-exported types from reth-op.
Migrates `crates/node` to use the `reth-op` meta-crate, …
> chore: migrate crates/node to use reth-op meta-crate
